<?php 
return [
'cnf_appname' 			=> 'Chhaya.xyz',
'cnf_appdesc' 			=> 'Chhaya.xyz',
'cnf_comname' 			=> 'Chhaya.xyz',
'cnf_email' 			=> 'info@chhaya.xyz',
'cnf_metakey' 			=> 'Chhaya.xyz',
'cnf_metadesc' 		=> 'Chhaya.xyz',
'cnf_group' 			=> '7',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '0',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'true',
'cnf_front' 			=> 'true',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '6LcRV_kUAAAAAPGCyIWOfrbeqprkF9kVF3poYEmA',
'cnf_recaptchaprivatekey' => '6LcRV_kUAAAAADsdKAuJcKh7YdYV1-iskkddEHF4',
'cnf_mode' 			=> 'development',
'cnf_logo' 			=> 'backend-logo.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '',
'cnf_mail' 			=> 'phpmail',
'cnf_maps' 			=> 'AIzaSyAayRr-0yZ1ejGGX6l--XDVbHWU85wPj9U',
'cnf_date' 			=> 'Y-m-d',
];
